### ISSUE TITLE
axios封装的用法真好, 学习了

### ISSUE THREAD

**Issue by qiqingfu** [xuexb/learn-vue2#2]

**Comment by xuexb** [comment]
Hi @qiqingfu ，我刚又更新了使用 axios 的一些逻辑，<https://github.com/xuexb/learn-vue2/tree/master/9-axios> ，这也是我们一直在用的方法，提炼了精华出来，也希望给小伙伴们一些启发，思路明确后方法都是相通的。

**Comment by qiqingfu** [comment]
@xuexb 看到更新了, 👍。这个项目价值很大

**Comment by xuexb** [comment]
哈哈哈，谈不上价值很大，我写这个项目的初衷本身也是想给『刚需』的人提供参考价值。需要她的人会感觉很受用，因为确实有一些坑和小技巧。而对于不需要她的人，其实就是一个简单的 Vue.js 项目默认模板而已。

本身项目也不是死的，至于怎么落地到自己项目中，大家自己也有自己的想法~
